import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Text, Box, Button } from "../components/atoms";
import { Card } from "../components/molecules";
import { CodeIcon } from "../components/icons";
import HeroSection from "../components/organisms/HeroSection/HeroSection";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Obol ui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text css={{ fontWeight: "$bold" }}>Test</Text>
        <h1 className={styles.title}>Welcome to Obol ui</h1>
        <Card
          heading="Heading"
          image="/image-card.png"
          variant="image"
          subheading="The Obol Network will forever be open source and permissionless. The impact of distributed validators lies in their accessibility."
          link="https://obol.tech"
        />
        <Box css={{ mt: "$xl" }} />
        <Card
          heading="Heading"
          image={<CodeIcon />}
          subheading="The Obol Network will forever be open source and permissionless. The impact of distributed validators lies in their accessibility."
          link="https://obol.tech"
        />
        <HeroSection
          css={{
            "& #heading-text": {
              width: "80%",
            },
          }}
          heading="Distribute Your Validators"
          content="Create an Obol Cluster solo or with a group using the Distributed Validator Launchpad"
        ></HeroSection>
      </main>
      DV Launchpad
      <HeroSection
        heading="Building Distributed Validators for Ethereum"
        content={
          <>
            The Obol Network is an ecosystem for trust minimized staking that
            allows people to{" "}
            <Text css={{ display: "inline-block" }} color="create" glow>
              create
            </Text>
            ,
            <Text css={{ display: "inline" }} color="test" glow>
              {" "}
              test
            </Text>
            ,
            <Text css={{ display: "inline" }} color="obolGreen" glow>
              {" "}
              run
            </Text>{" "}
            &
            <Text css={{ display: "inline" }} color="coordinate" glow>
              {" "}
              co-ordinate
            </Text>{" "}
            distributed validators
          </>
        }
      >
        <Button>Read the Docs</Button>
      </HeroSection>
      <footer className={styles.footer}>
        <a href="https://obol.tech" target="_blank" rel="noopener noreferrer">
          Powered by obol.tech
        </a>
      </footer>
    </div>
  );
};

export default Home;
