name: Publishing patch version

on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install
      - run: git config --global user.name "f1lander"
      - run: git config --global user.email "filanderuclez@gmail.com"
      # upgrade npm version in package.json to the tag used in the release.
      - run: npm version patch

      - name: Build package
        run: yarn ds:build

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
          scope: "@obolnetwork"

      - name: Publish package
        run: git push --follow-tags origin main && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git push
